version: '3.9'

services:
  sprint-db:
    container_name: sprint-db
    image: mongo
    networks: 
      - default
    ports: 
      - "27018:27017"
    volumes: 
      - mongodbdata:/data/db/sprint

  sprint-service:
    container_name: sprint-service
    build:
      context: .
      dockerfile: Sprint-Service/Dockerfile
    ports:
      - 5005:80
    networks:
      - default
    environment:
      ASPNETCORE_ENVIRONMENT: Staging

networks:
  default:
    name: swsp

volumes:
  mongodbdata: