version: '3.9'

services:
  sprint-db:
    container_name: sprint-db
    image: mongo
    networks: 
      - default
    ports: 
      - "27018:27017"
    volumes: 
      - mongodbdata:/data/db/sprint

networks:
  default:
    name: swsp

volumes:
  mongodbdata: